# restaurant_finding_task:
#   description: >
#     Find the best restaurants in the {location} area. If you unable to find any restaurants, please let the user know, politely.
#   expected_output: >
#     A list of the top 10 restaurants in the {location} area.
#   agent: restaurant_finder


ninive_menu_finding_task:
  description: >
    Find the menu of the Ninive restaurant. If you unable to find the menu, please let the user know, politely.
  expected_output: >
    The menu of the Ninive restaurant.
  agent: ninive_menu_finder