writering_task:
  description: >
   Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    Need a one paragraph explanation about {topic}
  agent: content_writer


translating_task:
  description: >
    Translate the article about {topic} into {language}
  expected_output: >
    A translated article about {topic} in {language}
  agent: content_translator